# Generated by Django 5.2.7 on 2025-11-24 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('placa', models.CharField(help_text='Ej: OBM0979-ABC1234', max_length=20, verbose_name='Placa del Vehículo')),
                ('numero_autorizacion', models.CharField(help_text='Ej: ACT-EP-DPOTTTM-016-2025-ACVIL', max_length=30, unique=True, verbose_name='Número de Autorización')),
                ('vigencia', models.DateField(verbose_name='Vigencia de Autorización')),
                ('codigo_qr', models.TextField(blank=True, help_text='URL del código QR generado', null=True, verbose_name='Código QR')),
                ('qr_generado', models.BooleanField(default=False, verbose_name='QR Generado')),
                ('fecha_descarga_qr', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Descarga QR')),
                ('fecha_descarga_pdf', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Descarga PDF')),
            ],
            options={
                'verbose_name': 'Autorización',
                'verbose_name_plural': 'Autorizaciones',
                'db_table': 'formulario_autorizacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acción')),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'db_table': 'formulario_historial_acciones',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Historial de Autorización',
                'verbose_name_plural': 'Historial de Autorizaciones',
                'db_table': 'formulario_historial_autorizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Autorización',
                'verbose_name_plural': 'Tipos de Autorización',
                'db_table': 'formulario_tipo_autorizacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres Completos')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe comenzar con 09 y tener 10 dígitos', regex='^09\\d{8}$')], verbose_name='Cédula')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener 13 dígitos', regex='^\\d{13}$')], verbose_name='RUC')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe comenzar con 09 y tener 10 dígitos', regex='^09\\d{8}$')], verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Usuario con Autorización',
                'verbose_name_plural': 'Usuarios con Autorización',
                'db_table': 'formulario_usuario_autorizacion',
                'ordering': ['nombres'],
            },
        ),
    ]
