# Generated by Django 5.2.7 on 2025-11-24 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='historialacciones',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_acciones', to='formulario.autorizacion'),
        ),
        migrations.AddField(
            model_name='historialacciones',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_acciones_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la acción'),
        ),
        migrations.AddField(
            model_name='historialautorizacion',
            name='autorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='formulario.autorizacion', verbose_name='Autorización'),
        ),
        migrations.AddField(
            model_name='historialautorizacion',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_autorizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
        migrations.AddField(
            model_name='tipoautorizacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='tipo_autorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='formulario.tipoautorizacion', verbose_name='Tipo de Autorización'),
        ),
        migrations.AddField(
            model_name='usuarioautorizacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='formulario.usuarioautorizacion', verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='historialautorizacion',
            index=models.Index(fields=['fecha_creacion'], name='formulario__fecha_c_61b4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialautorizacion',
            index=models.Index(fields=['-fecha_creacion'], name='formulario__fecha_c_a78caa_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioautorizacion',
            index=models.Index(fields=['cedula'], name='formulario__cedula_a56719_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioautorizacion',
            index=models.Index(fields=['ruc'], name='formulario__ruc_09812e_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioautorizacion',
            index=models.Index(fields=['correo'], name='formulario__correo_c363eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioautorizacion',
            index=models.Index(fields=['nombres'], name='formulario__nombres_d7e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['placa'], name='formulario__placa_22fb08_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['numero_autorizacion'], name='formulario__numero__2b9ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['vigencia'], name='formulario__vigenci_f0f225_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['fecha_creacion'], name='formulario__fecha_c_2cd7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['activo'], name='formulario__activo_52e081_idx'),
        ),
        migrations.AddConstraint(
            model_name='autorizacion',
            constraint=models.UniqueConstraint(fields=('usuario', 'placa', 'tipo_autorizacion'), name='unique_usuario_placa_tipo'),
        ),
    ]
