# Generated by Django 5.2.7 on 2025-11-23 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_creacion_autorizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='formulario.autorizacion', verbose_name='Autorización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_autorizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Historial de Autorización',
                'verbose_name_plural': 'Historial de Autorizaciones',
                'db_table': 'formulario_historial_autorizaciones',
                'ordering': ['-fecha_creacion_autorizacion'],
                'indexes': [models.Index(fields=['fecha_creacion_autorizacion'], name='formulario__fecha_c_91b9b1_idx'), models.Index(fields=['-fecha_creacion_autorizacion'], name='formulario__fecha_c_3e062d_idx')],
            },
        ),
    ]
