# Generated by Django 5.2.7 on 2025-11-23 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_historialautorizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialautorizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Historial de Autorización', 'verbose_name_plural': 'Historial de Autorizaciones'},
        ),
        migrations.RemoveIndex(
            model_name='historialautorizacion',
            name='formulario__fecha_c_91b9b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialautorizacion',
            name='formulario__fecha_c_3e062d_idx',
        ),
        migrations.RemoveField(
            model_name='historialautorizacion',
            name='fecha_creacion_autorizacion',
        ),
        migrations.AddIndex(
            model_name='historialautorizacion',
            index=models.Index(fields=['fecha_creacion'], name='formulario__fecha_c_61b4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialautorizacion',
            index=models.Index(fields=['-fecha_creacion'], name='formulario__fecha_c_a78caa_idx'),
        ),
    ]
