# Generated by Django 5.2.7 on 2025-10-17 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_usuarioautorizacion_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioautorizacion',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe comenzar con 09 y tener 10 dígitos', regex='^09\\d{8}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='usuarioautorizacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe comenzar con 09 y tener 10 dígitos', regex='^09\\d{8}$')], verbose_name='Teléfono'),
        ),
    ]
