# Generated by Django 5.2.7 on 2025-11-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_usuarioautorizacion_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialautorizacion',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='formulario.autorizacion'),
        ),
    ]
